create schema if not exists private;

create table if not exists private.api_usage_windows (
  user_id uuid not null references auth.users(id) on delete cascade,
  recurso text not null,
  janela_inicio timestamptz not null,
  quantidade integer not null default 0 check (quantidade >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, recurso, janela_inicio)
);

create table if not exists private.consent_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tipo_evento text not null,
  aceito boolean not null,
  ip inet,
  user_agent text,
  metadados jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists idx_consent_events_user_created
on private.consent_events (user_id, criado_em desc);

create or replace function public.consumir_cota_api(
  p_user_id uuid,
  p_recurso text,
  p_quantidade integer,
  p_limite integer,
  p_janela_minutos integer default 60
)
returns table (permitido boolean, restante integer, reset_at timestamptz)
language plpgsql
security definer
set search_path = private, public
as $$
declare
  v_janela_inicio timestamptz;
  v_reset_at timestamptz;
  v_quantidade_atual integer;
begin
  if p_user_id is null or nullif(trim(p_recurso), '') is null then
    raise exception 'Parâmetros de cota inválidos';
  end if;

  if p_quantidade <= 0 or p_limite <= 0 or p_janela_minutos <= 0 then
    raise exception 'Limites de cota inválidos';
  end if;

  v_janela_inicio := to_timestamp(
    floor(extract(epoch from now()) / (p_janela_minutos * 60)) * (p_janela_minutos * 60)
  );
  v_reset_at := v_janela_inicio + make_interval(mins => p_janela_minutos);

  insert into private.api_usage_windows (user_id, recurso, janela_inicio, quantidade)
  values (p_user_id, p_recurso, v_janela_inicio, p_quantidade)
  on conflict (user_id, recurso, janela_inicio)
  do update set
    quantidade = private.api_usage_windows.quantidade + excluded.quantidade,
    updated_at = now()
  returning quantidade into v_quantidade_atual;

  permitido := v_quantidade_atual <= p_limite;
  restante := greatest(0, p_limite - v_quantidade_atual);
  reset_at := v_reset_at;
  return next;
end;
$$;

create or replace function public.registrar_evento_consentimento(
  p_user_id uuid,
  p_tipo_evento text,
  p_aceito boolean,
  p_ip text default null,
  p_user_agent text default null,
  p_metadados jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
begin
  if p_user_id is null or nullif(trim(p_tipo_evento), '') is null then
    raise exception 'Evento de consentimento inválido';
  end if;

  insert into private.consent_events (user_id, tipo_evento, aceito, ip, user_agent, metadados)
  values (
    p_user_id,
    trim(p_tipo_evento),
    p_aceito,
    nullif(trim(coalesce(p_ip, '')), '')::inet,
    nullif(trim(coalesce(p_user_agent, '')), ''),
    coalesce(p_metadados, '{}'::jsonb)
  );
end;
$$;

revoke all on schema private from public, anon, authenticated;
revoke all on all tables in schema private from public, anon, authenticated;
revoke all on function public.consumir_cota_api(uuid, text, integer, integer, integer) from public, anon, authenticated;
revoke all on function public.registrar_evento_consentimento(uuid, text, boolean, text, text, jsonb) from public, anon, authenticated;

grant execute on function public.consumir_cota_api(uuid, text, integer, integer, integer) to service_role;
grant execute on function public.registrar_evento_consentimento(uuid, text, boolean, text, text, jsonb) to service_role;

revoke delete on public.profiles from anon, authenticated;
revoke truncate on public.profiles from anon, authenticated;
revoke insert, update on public.profiles from anon, authenticated;

alter table public.profiles drop constraint if exists profiles_email_consent_required_check;
alter table public.profiles drop constraint if exists profiles_whatsapp_consent_required_check;

drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
