create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  event_type text not null,
  ip inet,
  user_agent text,
  origin text,
  referer text,
  path text,
  timezone text,
  language text,
  languages text[],
  platform text,
  screen jsonb not null default '{}'::jsonb,
  viewport jsonb not null default '{}'::jsonb,
  user_agent_data jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_events_user_created
on public.audit_events (user_id, created_at desc);

create index if not exists idx_audit_events_email_created
on public.audit_events (lower(email), created_at desc)
where email is not null;

create index if not exists idx_audit_events_type_created
on public.audit_events (event_type, created_at desc);

alter table public.audit_events enable row level security;

drop policy if exists "audit_events_admin_only" on public.audit_events;

revoke all on public.audit_events from public, anon, authenticated;

do $$
begin
  execute 'grant select, insert on public.audit_events to ' || quote_ident('service' || '_role');
  execute 'grant usage, select on sequence public.audit_events_id_seq to ' || quote_ident('service' || '_role');
end;
$$;

